spring:
    profiles:  
        active: local
    datasource:
        url: jdbc:h2:tcp://localhost/~/querydsl
        username: sa
        password: 
        driver-class-name: org.h2.Driver

    jpa:
        hibernate:
            ddl-auto: create 
        properties:
            hibernate:
                # dialect: org.hibernate.dialect.Oracle10gDialect
                format_sql: true
                # use_sql_comments: true
                # show_sql: true
                default_batch_fetch_size: 300 
                # OneToMany 의 collection 정보를 미리 사이즈 만큼 가져 옴
                # 그래서 쿼리가 collection 갯수 만큼 발생되지 않는 장점
    
    devtools:
        livereload:
           enabled: true
        restart:
            enabled: false 
    
    data:
        web:
            pageable:
                default-page-size: 10 # default 20
                max-page-size: 1000

logging: 
    level: 
        org.hibernate.SQL: debug
        # org.hibernate.type: trace
