spring:
    profiles: 
        activie: test
    devtools:
        livereload:
           enabled: true
        restart:
            enabled: false 
    jpa:
        properties:
            hibernate:
                format_sql: true
                # show_sql: true
                default_batch_fetch_size: 300 
                # OneToMany 의 collection 정보를 미리 사이즈 만큼 가져 옴
                # 그래서 쿼리가 collection 갯수 만큼 발생되지 않는 장점 
logging: 
    level: 
        org.hibernate.SQL: debug
        # org.hibernate.type: trace
